//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 05:57:57 PM MSK 
//


package com.example.soap.sberbank.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class EnumValutesFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public EnumValutesFactory() {
    }

    /**
     * Create an instance of {@link EnumValutesXMLResponse }
     * 
     */
    public EnumValutesXMLResponse createEnumValutesXMLResponse() {
        return new EnumValutesXMLResponse();
    }

    /**
     * Create an instance of {@link EnumValutesXMLResponse.EnumValutesXMLResult }
     * 
     */
    public EnumValutesXMLResponse.EnumValutesXMLResult createEnumValutesXMLResponseEnumValutesXMLResult() {
        return new EnumValutesXMLResponse.EnumValutesXMLResult();
    }

    /**
     * Create an instance of {@link EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData }
     * 
     */
    public EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData createEnumValutesXMLResponseEnumValutesXMLResultValuteData() {
        return new EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData();
    }

    /**
     * Create an instance of {@link EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData.EnumValutes }
     * 
     */
    public EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData.EnumValutes createEnumValutesXMLResponseEnumValutesXMLResultValuteDataEnumValutes() {
        return new EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData.EnumValutes();
    }

}
