//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 05:57:57 PM MSK 
//


package com.example.soap.sberbank.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EnumValutesXMLResult"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ValuteData"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="EnumValutes" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="VEngname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="VcommonCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="VnumCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="VcharCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enumValutesXMLResult"
})
@XmlRootElement(name = "EnumValutesXMLResponse")
public class EnumValutesXMLResponse {

    @XmlElement(name = "EnumValutesXMLResult", required = true)
    protected EnumValutesXMLResponse.EnumValutesXMLResult enumValutesXMLResult;

    /**
     * Gets the value of the enumValutesXMLResult property.
     *
     * @return
     *     possible object is
     *     {@link EnumValutesXMLResponse.EnumValutesXMLResult }
     *
     */
    public EnumValutesXMLResponse.EnumValutesXMLResult getEnumValutesXMLResult() {
        return enumValutesXMLResult;
    }

    /**
     * Sets the value of the enumValutesXMLResult property.
     *
     * @param value
     *     allowed object is
     *     {@link EnumValutesXMLResponse.EnumValutesXMLResult }
     *
     */
    public void setEnumValutesXMLResult(EnumValutesXMLResponse.EnumValutesXMLResult value) {
        this.enumValutesXMLResult = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ValuteData"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="EnumValutes" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="VEngname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="VcommonCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="VnumCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="VcharCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "valuteData"
    })
    public static class EnumValutesXMLResult {

        @XmlElement(name = "ValuteData", required = true)
        protected EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData valuteData;

        /**
         * Gets the value of the valuteData property.
         *
         * @return
         *     possible object is
         *     {@link EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData }
         *
         */
        public EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData getValuteData() {
            return valuteData;
        }

        /**
         * Sets the value of the valuteData property.
         *
         * @param value
         *     allowed object is
         *     {@link EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData }
         *
         */
        public void setValuteData(EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData value) {
            this.valuteData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="EnumValutes" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="VEngname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="VcommonCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="VnumCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="VcharCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "enumValutes"
        })
        public static class ValuteData {

            @XmlElement(name = "EnumValutes", required = true)
            protected List<EnumValutes> enumValutes;

            /**
             * Gets the value of the enumValutes property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the enumValutes property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEnumValutes().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link EnumValutesXMLResponse.EnumValutesXMLResult.ValuteData.EnumValutes }
             *
             *
             */
            public List<EnumValutes> getEnumValutes() {
                if (enumValutes == null) {
                    enumValutes = new ArrayList<EnumValutes>();
                }
                return this.enumValutes;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="VEngname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="VcommonCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="VnumCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="VcharCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "vcode",
                "vname",
                "vEngname",
                "vnom",
                "vcommonCode",
                "vnumCode",
                "vcharCode"
            })
            public static class EnumValutes {

                @XmlElement(name = "Vcode", required = true)
                protected String vcode;
                @XmlElement(name = "Vname", required = true)
                protected String vname;
                @XmlElement(name = "VEngname", required = true)
                protected String vEngname;
                @XmlElement(name = "Vnom")
                protected int vnom;
                @XmlElement(name = "VcommonCode", required = true)
                protected String vcommonCode;
                @XmlElement(name = "VnumCode")
                protected int vnumCode;
                @XmlElement(name = "VcharCode", required = true)
                protected String vcharCode;

                /**
                 * Gets the value of the vcode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVcode() {
                    return vcode;
                }

                /**
                 * Sets the value of the vcode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVcode(String value) {
                    this.vcode = value;
                }

                /**
                 * Gets the value of the vname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVname() {
                    return vname;
                }

                /**
                 * Sets the value of the vname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVname(String value) {
                    this.vname = value;
                }

                /**
                 * Gets the value of the vEngname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVEngname() {
                    return vEngname;
                }

                /**
                 * Sets the value of the vEngname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVEngname(String value) {
                    this.vEngname = value;
                }

                /**
                 * Gets the value of the vnom property.
                 * 
                 */
                public int getVnom() {
                    return vnom;
                }

                /**
                 * Sets the value of the vnom property.
                 * 
                 */
                public void setVnom(int value) {
                    this.vnom = value;
                }

                /**
                 * Gets the value of the vcommonCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVcommonCode() {
                    return vcommonCode;
                }

                /**
                 * Sets the value of the vcommonCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVcommonCode(String value) {
                    this.vcommonCode = value;
                }

                /**
                 * Gets the value of the vnumCode property.
                 * 
                 */
                public int getVnumCode() {
                    return vnumCode;
                }

                /**
                 * Sets the value of the vnumCode property.
                 * 
                 */
                public void setVnumCode(int value) {
                    this.vnumCode = value;
                }

                /**
                 * Gets the value of the vcharCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVcharCode() {
                    return vcharCode;
                }

                /**
                 * Sets the value of the vcharCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVcharCode(String value) {
                    this.vcharCode = value;
                }

            }

        }

    }

}
