//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 06:09:35 PM MSK 
//


package com.example.soap.sberbank.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class GetCursOnDateFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public GetCursOnDateFactory() {
    }

    /**
     * Create an instance of {@link GetCursOnDateXMLResponse }
     * 
     */
    public GetCursOnDateXMLResponse createGetCursOnDateXMLResponse() {
        return new GetCursOnDateXMLResponse();
    }

    /**
     * Create an instance of {@link GetCursOnDateXMLResponse.GetCursOnDateXMLResult }
     * 
     */
    public GetCursOnDateXMLResponse.GetCursOnDateXMLResult createGetCursOnDateXMLResponseGetCursOnDateXMLResult() {
        return new GetCursOnDateXMLResponse.GetCursOnDateXMLResult();
    }

    /**
     * Create an instance of {@link GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData }
     * 
     */
    public GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData createGetCursOnDateXMLResponseGetCursOnDateXMLResultValuteData() {
        return new GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData();
    }

    /**
     * Create an instance of {@link GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData.ValuteCursOnDate }
     * 
     */
    public GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData.ValuteCursOnDate createGetCursOnDateXMLResponseGetCursOnDateXMLResultValuteDataValuteCursOnDate() {
        return new GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData.ValuteCursOnDate();
    }

}
