//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.17 at 06:09:35 PM MSK 
//


package com.example.soap.sberbank.response;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetCursOnDateXMLResult"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ValuteData"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ValuteCursOnDate" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="Vcurs" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="VchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="OnDate" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "getCursOnDateXMLResult"
})
@XmlRootElement(name = "GetCursOnDateXMLResponse")
public class GetCursOnDateXMLResponse {

    @XmlElement(name = "GetCursOnDateXMLResult", required = true, namespace = "http://web.cbr.ru/")
    protected GetCursOnDateXMLResponse.GetCursOnDateXMLResult getCursOnDateXMLResult;

    /**
     * Gets the value of the getCursOnDateXMLResult property.
     *
     * @return
     *     possible object is
     *     {@link GetCursOnDateXMLResponse.GetCursOnDateXMLResult }
     *
     */
    public GetCursOnDateXMLResponse.GetCursOnDateXMLResult getGetCursOnDateXMLResult() {
        return getCursOnDateXMLResult;
    }

    /**
     * Sets the value of the getCursOnDateXMLResult property.
     *
     * @param value
     *     allowed object is
     *     {@link GetCursOnDateXMLResponse.GetCursOnDateXMLResult }
     *
     */
    public void setGetCursOnDateXMLResult(GetCursOnDateXMLResponse.GetCursOnDateXMLResult value) {
        this.getCursOnDateXMLResult = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ValuteData"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ValuteCursOnDate" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="Vcurs" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                             &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="VchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="OnDate" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "valuteData"
    })
    public static class GetCursOnDateXMLResult {

        @XmlElement(name = "ValuteData", required = true, namespace = "")
        protected GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData valuteData;

        /**
         * Gets the value of the valuteData property.
         *
         * @return
         *     possible object is
         *     {@link GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData }
         *
         */
        public GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData getValuteData() {
            return valuteData;
        }

        /**
         * Sets the value of the valuteData property.
         *
         * @param value
         *     allowed object is
         *     {@link GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData }
         *
         */
        public void setValuteData(GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData value) {
            this.valuteData = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ValuteCursOnDate" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="Vcurs" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
         *                   &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="VchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="OnDate" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "valuteCursOnDate"
        })
        public static class ValuteData {

            @XmlElement(name = "ValuteCursOnDate", required = true, namespace = "")
            protected List<GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData.ValuteCursOnDate> valuteCursOnDate;
            @XmlAttribute(name = "OnDate")
            protected Integer onDate;

            /**
             * Gets the value of the valuteCursOnDate property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the valuteCursOnDate property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValuteCursOnDate().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData.ValuteCursOnDate }
             *
             *
             */
            public List<GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData.ValuteCursOnDate> getValuteCursOnDate() {
                if (valuteCursOnDate == null) {
                    valuteCursOnDate = new ArrayList<GetCursOnDateXMLResponse.GetCursOnDateXMLResult.ValuteData.ValuteCursOnDate>();
                }
                return this.valuteCursOnDate;
            }

            /**
             * Gets the value of the onDate property.
             *
             * @return
             *     possible object is
             *     {@link Integer }
             *
             */
            public Integer getOnDate() {
                return onDate;
            }

            /**
             * Sets the value of the onDate property.
             *
             * @param value
             *     allowed object is
             *     {@link Integer }
             *
             */
            public void setOnDate(Integer value) {
                this.onDate = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="Vcurs" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
             *         &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="VchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "vname",
                    "vnom",
                    "vcurs",
                    "vcode",
                    "vchCode"
            })
            public static class ValuteCursOnDate {

                @XmlElement(name = "Vname", required = true, namespace = "")
                protected String vname;
                @XmlElement(name = "Vnom", namespace = "")
                protected int vnom;
                @XmlElement(name = "Vcurs", required = true, namespace = "")
                protected BigDecimal vcurs;
                @XmlElement(name = "Vcode", namespace = "")
                protected int vcode;
                @XmlElement(name = "VchCode", required = true, namespace = "")
                protected String vchCode;

                /**
                 * Gets the value of the vname property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getVname() {
                    return vname;
                }

                /**
                 * Sets the value of the vname property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setVname(String value) {
                    this.vname = value;
                }

                /**
                 * Gets the value of the vnom property.
                 *
                 */
                public int getVnom() {
                    return vnom;
                }

                /**
                 * Sets the value of the vnom property.
                 *
                 */
                public void setVnom(int value) {
                    this.vnom = value;
                }

                /**
                 * Gets the value of the vcurs property.
                 *
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *
                 */
                public BigDecimal getVcurs() {
                    return vcurs;
                }

                /**
                 * Sets the value of the vcurs property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *
                 */
                public void setVcurs(BigDecimal value) {
                    this.vcurs = value;
                }

                /**
                 * Gets the value of the vcode property.
                 *
                 */
                public int getVcode() {
                    return vcode;
                }

                /**
                 * Sets the value of the vcode property.
                 *
                 */
                public void setVcode(int value) {
                    this.vcode = value;
                }

                /**
                 * Gets the value of the vchCode property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getVchCode() {
                    return vchCode;
                }

                /**
                 * Sets the value of the vchCode property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setVchCode(String value) {
                    this.vchCode = value;
                }

            }

        }

    }

}
