//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.07 at 10:10:13 PM MSK 
//


package com.example.soap.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated2 package. 
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class GetCursOnDateXMLFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated2
     * 
     */
    public GetCursOnDateXMLFactory() {
    }

    /**
     * Create an instance of {@link GetCursOnDateXMLData }
     * 
     */
    public GetCursOnDateXMLData createValuteData() {
        return new GetCursOnDateXMLData();
    }

    /**
     * Create an instance of {@link GetCursOnDateXMLData.ValuteCursOnDate }
     * 
     */
    public GetCursOnDateXMLData.ValuteCursOnDate createValuteDataValuteCursOnDate() {
        return new GetCursOnDateXMLData.ValuteCursOnDate();
    }

}
