//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.07 at 10:10:13 PM MSK 
//


package com.example.soap.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ValuteCursOnDate" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="Vcurs" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                   &lt;element name="VchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="OnDate" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valuteCursOnDate"
})
@XmlRootElement(name = "ValuteData")
public class GetCursOnDateXMLData {

    @XmlElement(name = "ValuteCursOnDate")
    protected List<ValuteCursOnDate> valuteCursOnDate;
    @XmlAttribute(name = "OnDate")
    protected Integer onDate;

    /**
     * Gets the value of the valuteCursOnDate property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuteCursOnDate property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuteCursOnDate().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetCursOnDateXMLData.ValuteCursOnDate }
     *
     *
     */
    public List<ValuteCursOnDate> getValuteCursOnDate() {
        if (valuteCursOnDate == null) {
            valuteCursOnDate = new ArrayList<ValuteCursOnDate>();
        }
        return this.valuteCursOnDate;
    }

    /**
     * Gets the value of the onDate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOnDate() {
        return onDate;
    }

    /**
     * Sets the value of the onDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOnDate(Integer value) {
        this.onDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Vname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="Vcurs" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *         &lt;element name="VchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vname",
        "vnom",
        "vcurs",
        "vcode",
        "vchCode"
    })
    public static class ValuteCursOnDate {

        @XmlElement(name = "Vname", required = true)
        protected String vname;
        @XmlElement(name = "Vnom")
        protected short vnom;
        @XmlElement(name = "Vcurs")
        protected float vcurs;
        @XmlElement(name = "Vcode")
        protected short vcode;
        @XmlElement(name = "VchCode", required = true)
        protected String vchCode;

        /**
         * Gets the value of the vname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVname() {
            return vname;
        }

        /**
         * Sets the value of the vname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVname(String value) {
            this.vname = value;
        }

        /**
         * Gets the value of the vnom property.
         * 
         */
        public short getVnom() {
            return vnom;
        }

        /**
         * Sets the value of the vnom property.
         * 
         */
        public void setVnom(short value) {
            this.vnom = value;
        }

        /**
         * Gets the value of the vcurs property.
         * 
         */
        public float getVcurs() {
            return vcurs;
        }

        /**
         * Sets the value of the vcurs property.
         * 
         */
        public void setVcurs(float value) {
            this.vcurs = value;
        }

        /**
         * Gets the value of the vcode property.
         * 
         */
        public short getVcode() {
            return vcode;
        }

        /**
         * Sets the value of the vcode property.
         * 
         */
        public void setVcode(short value) {
            this.vcode = value;
        }

        /**
         * Gets the value of the vchCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVchCode() {
            return vchCode;
        }

        /**
         * Sets the value of the vchCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVchCode(String value) {
            this.vchCode = value;
        }

    }

}
